# Generated by Django 5.2 on 2025-04-15 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='apartment_area',
            field=models.FloatField(default=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimate',
            name='ceiling_height',
            field=models.FloatField(default=2.4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimate',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estimate',
            name='name',
            field=models.CharField(default='Смета #1', max_length=255),
        ),
    ]
