# Generated by Django 5.2 on 2025-04-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0002_estimate_apartment_area_estimate_ceiling_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
