# Generated by Django 5.2 on 2025-04-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0004_estimate_total_cost_alter_estimate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='bathroom_area',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='estimate',
            name='has_replanning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estimate',
            name='kitchen_area',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='estimate',
            name='material_quality',
            field=models.CharField(choices=[('economy', 'Эконом'), ('standard', 'Стандарт'), ('premium', 'Премиум')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='estimate',
            name='num_bathrooms',
            field=models.IntegerField(default=1),
        ),
    ]
